services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 40s ; python ./app.py"
    depends_on:
      - mysql

  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'bisidb'
      MYSQL_ROOT_PASSWORD: '*********'
    ports:
      - '8080:3306'
   
    